import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Space Grotesk', 'Inter', 'system-ui', 'sans-serif'],
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      letterSpacing: {
        tightest: '-0.04em',
        tighter: '-0.025em',
        tight: '-0.015em',
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        medical: {
          green: "hsl(var(--medical-green))",
          blue: "hsl(var(--medical-blue))",
          teal: "hsl(var(--medical-teal))",
        },
        // Google Stitch — Material Design 3 Medical tokens
        "inverse-primary": "#a9f7eb",
        "on-secondary-fixed": "#224543",
        "tertiary-container": "#b6e7fe",
        "primary-dim": "#005e56",
        "on-surface-variant": "#586160",
        "tertiary": "#346578",
        "on-surface": "#2c3434",
        "on-primary-fixed-variant": "#0a675e",
        "outline-variant": "#abb4b3",
        "outline": "#737c7c",
        "on-tertiary-container": "#235669",
        "on-secondary-fixed-variant": "#3f625f",
        "surface-variant": "#dbe4e3",
        "tertiary-dim": "#26596c",
        "surface-bright": "#f7faf9",
        "primary-fixed-dim": "#96e2d7",
        "on-primary-fixed": "#004842",
        "surface": "#f7faf9",
        "on-tertiary": "#f2faff",
        "surface-container-high": "#e2eae9",
        "on-background": "#2c3434",
        "on-tertiary-fixed-variant": "#2e6073",
        "secondary-dim": "#375956",
        "secondary-fixed": "#c4eae6",
        "on-secondary-container": "#355855",
        "on-primary": "#e2fff9",
        "inverse-on-surface": "#9a9e9d",
        "surface-dim": "#d3dcdb",
        "error-container": "#fa746f",
        "on-error": "#fff7f6",
        "primary-fixed": "#a4f1e5",
        "inverse-surface": "#0b0f0f",
        "secondary-container": "#c4eae6",
        "on-secondary": "#e1fffc",
        "secondary-fixed-dim": "#b7dcd8",
        "primary-container": "#a4f1e5",
        "surface-container-low": "#f0f5f4",
        "surface-container": "#e9efee",
        "tertiary-fixed": "#b6e7fe",
        "on-error-container": "#6e0a12",
        "tertiary-fixed-dim": "#a8d9ef",
        "surface-tint": "#126b62",
        "surface-container-highest": "#dbe4e3",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#005c54",
        "on-tertiary-fixed": "#074355",
        "error-dim": "#67040d",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 1px)",
        sm: "calc(var(--radius) - 3px)",
      },
      boxShadow: {
        // Apple-style ambient light shadows — barely there
        'subtle':    '0 1px 2px 0 rgb(0 0 0 / 0.04)',
        'card':      '0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.04)',
        'elevated':  '0 4px 12px -2px rgb(0 0 0 / 0.07), 0 2px 4px -2px rgb(0 0 0 / 0.04)',
        'modal':     '0 12px 24px -4px rgb(0 0 0 / 0.10), 0 4px 8px -4px rgb(0 0 0 / 0.06)',
        'focus':     '0 0 0 3px hsl(var(--ring) / 0.15)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 12px hsl(var(--medical-green) / 0.18)" },
          "50%": { boxShadow: "0 0 24px hsl(var(--medical-green) / 0.30)" },
        },
        "wave": {
          "0%, 100%": { transform: "translateY(0)", opacity: "0.35" },
          "50%": { transform: "translateY(-5px)", opacity: "1" },
        },
        "shimmer": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
        "fade-up": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "slide-in-left": {
          from: { opacity: "0", transform: "translateX(-12px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.95)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-4px)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "pulse-glow": "pulse-glow 2.5s ease-in-out infinite",
        "fade-up": "fade-up 0.4s ease-out both",
        "fade-up-delay-1": "fade-up 0.45s 0.05s ease-out both",
        "fade-up-delay-2": "fade-up 0.45s 0.10s ease-out both",
        "fade-up-delay-3": "fade-up 0.45s 0.15s ease-out both",
        "fade-up-delay-4": "fade-up 0.45s 0.20s ease-out both",
        "fade-in": "fade-in 0.3s ease-out both",
        "slide-in-left": "slide-in-left 0.35s ease-out both",
        "scale-in": "scale-in 0.25s ease-out both",
        "float": "float 3s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
